import { OxmlPartContainer } from '../framework/OxmlPartContainer';
import { OxmlPackage } from '../framework/OxmlPackage';
import { AlternativeFormatImportPart } from "./AlternativeFormatImportPart";
import { CalculationChainPart } from "./CalculationChainPart";
import { CellMetadataPart } from "./CellMetadataPart";
import { ChartColorStylePart } from "./ChartColorStylePart";
import { ChartDrawingPart } from "./ChartDrawingPart";
import { ChartPart } from "./ChartPart";
import { ChartStylePart } from "./ChartStylePart";
import { ChartsheetPart } from "./ChartsheetPart";
import { CommentAuthorsPart } from "./CommentAuthorsPart";
import { ConnectionsPart } from "./ConnectionsPart";
import { ControlPropertiesPart } from "./ControlPropertiesPart";
import { CoreFilePropertiesPart } from "./CoreFilePropertiesPart";
import { CustomDataPart } from "./CustomDataPart";
import { CustomDataPropertiesPart } from "./CustomDataPropertiesPart";
import { CustomFilePropertiesPart } from "./CustomFilePropertiesPart";
import { CustomPropertyPart } from "./CustomPropertyPart";
import { CustomXmlMappingsPart } from "./CustomXmlMappingsPart";
import { CustomXmlPart } from "./CustomXmlPart";
import { CustomXmlPropertiesPart } from "./CustomXmlPropertiesPart";
import { CustomizationPart } from "./CustomizationPart";
import { DiagramColorsPart } from "./DiagramColorsPart";
import { DiagramDataPart } from "./DiagramDataPart";
import { DiagramLayoutDefinitionPart } from "./DiagramLayoutDefinitionPart";
import { DiagramPersistLayoutPart } from "./DiagramPersistLayoutPart";
import { DiagramStylePart } from "./DiagramStylePart";
import { DialogsheetPart } from "./DialogsheetPart";
import { DigitalSignatureOriginPart } from "./DigitalSignatureOriginPart";
import { DocumentSettingsPart } from "./DocumentSettingsPart";
import { DocumentTasksPart } from "./DocumentTasksPart";
import { DrawingsPart } from "./DrawingsPart";
import { EmbeddedControlPersistenceBinaryDataPart } from "./EmbeddedControlPersistenceBinaryDataPart";
import { EmbeddedControlPersistencePart } from "./EmbeddedControlPersistencePart";
import { EmbeddedObjectPart } from "./EmbeddedObjectPart";
import { EmbeddedPackagePart } from "./EmbeddedPackagePart";
import { EndnotesPart } from "./EndnotesPart";
import { ExcelAttachedToolbarsPart } from "./ExcelAttachedToolbarsPart";
import { ExtendedChartPart } from "./ExtendedChartPart";
import { ExtendedFilePropertiesPart } from "./ExtendedFilePropertiesPart";
import { ExternalWorkbookPart } from "./ExternalWorkbookPart";
import { FontPart } from "./FontPart";
import { FontTablePart } from "./FontTablePart";
import { FooterPart } from "./FooterPart";
import { FootnotesPart } from "./FootnotesPart";
import { GlossaryDocumentPart } from "./GlossaryDocumentPart";
import { HandoutMasterPart } from "./HandoutMasterPart";
import { HeaderPart } from "./HeaderPart";
import { ImagePart } from "./ImagePart";
import { InternationalMacroSheetPart } from "./InternationalMacroSheetPart";
import { LabelInfoPart } from "./LabelInfoPart";
import { LegacyDiagramTextInfoPart } from "./LegacyDiagramTextInfoPart";
import { LegacyDiagramTextPart } from "./LegacyDiagramTextPart";
import { MacroSheetPart } from "./MacroSheetPart";
import { MailMergeRecipientDataPart } from "./MailMergeRecipientDataPart";
import { MainDocumentPart } from "./MainDocumentPart";
import { Model3DReferenceRelationshipPart } from "./Model3DReferenceRelationshipPart";
import { NamedSheetViewsPart } from "./NamedSheetViewsPart";
import { NotesMasterPart } from "./NotesMasterPart";
import { NotesSlidePart } from "./NotesSlidePart";
import { NumberingDefinitionsPart } from "./NumberingDefinitionsPart";
import { PivotTableCacheDefinitionPart } from "./PivotTableCacheDefinitionPart";
import { PivotTableCacheRecordsPart } from "./PivotTableCacheRecordsPart";
import { PivotTablePart } from "./PivotTablePart";
import { PowerPointAuthorsPart } from "./PowerPointAuthorsPart";
import { PowerPointCommentPart } from "./PowerPointCommentPart";
import { PresentationPart } from "./PresentationPart";
import { PresentationPropertiesPart } from "./PresentationPropertiesPart";
import { QueryTablePart } from "./QueryTablePart";
import { QuickAccessToolbarCustomizationsPart } from "./QuickAccessToolbarCustomizationsPart";
import { RdArrayPart } from "./RdArrayPart";
import { RdRichValuePart } from "./RdRichValuePart";
import { RdRichValueStructurePart } from "./RdRichValueStructurePart";
import { RdRichValueTypesPart } from "./RdRichValueTypesPart";
import { RdRichValueWebImagePart } from "./RdRichValueWebImagePart";
import { RdSupportingPropertyBagPart } from "./RdSupportingPropertyBagPart";
import { RdSupportingPropertyBagStructurePart } from "./RdSupportingPropertyBagStructurePart";
import { RibbonAndBackstageCustomizationsPart } from "./RibbonAndBackstageCustomizationsPart";
import { RibbonExtensibilityPart } from "./RibbonExtensibilityPart";
import { RichStylesPart } from "./RichStylesPart";
import { SharedStringTablePart } from "./SharedStringTablePart";
import { SingleCellTablePart } from "./SingleCellTablePart";
import { SlicerCachePart } from "./SlicerCachePart";
import { SlicersPart } from "./SlicersPart";
import { SlideCommentsPart } from "./SlideCommentsPart";
import { SlideLayoutPart } from "./SlideLayoutPart";
import { SlideMasterPart } from "./SlideMasterPart";
import { SlidePart } from "./SlidePart";
import { SlideSyncDataPart } from "./SlideSyncDataPart";
import { SpreadsheetPrinterSettingsPart } from "./SpreadsheetPrinterSettingsPart";
import { StyleDefinitionsPart } from "./StyleDefinitionsPart";
import { StylesWithEffectsPart } from "./StylesWithEffectsPart";
import { TableDefinitionPart } from "./TableDefinitionPart";
import { TableStylesPart } from "./TableStylesPart";
import { ThemeOverridePart } from "./ThemeOverridePart";
import { ThemePart } from "./ThemePart";
import { ThumbnailPart } from "./ThumbnailPart";
import { TimeLineCachePart } from "./TimeLineCachePart";
import { TimeLinePart } from "./TimeLinePart";
import { UserDefinedTagsPart } from "./UserDefinedTagsPart";
import { VbaDataPart } from "./VbaDataPart";
import { VbaProjectPart } from "./VbaProjectPart";
import { ViewPropertiesPart } from "./ViewPropertiesPart";
import { VmlDrawingPart } from "./VmlDrawingPart";
import { VolatileDependenciesPart } from "./VolatileDependenciesPart";
import { WebExTaskpanesPart } from "./WebExTaskpanesPart";
import { WebExtensionPart } from "./WebExtensionPart";
import { WebSettingsPart } from "./WebSettingsPart";
import { WordAttachedToolbarsPart } from "./WordAttachedToolbarsPart";
import { WordCommentsExtensiblePart } from "./WordCommentsExtensiblePart";
import { WordprocessingCommentsExPart } from "./WordprocessingCommentsExPart";
import { WordprocessingCommentsIdsPart } from "./WordprocessingCommentsIdsPart";
import { WordprocessingCommentsPart } from "./WordprocessingCommentsPart";
import { WordprocessingPeoplePart } from "./WordprocessingPeoplePart";
import { WordprocessingPrinterSettingsPart } from "./WordprocessingPrinterSettingsPart";
import { WorkbookPart } from "./WorkbookPart";
import { WorkbookPersonPart } from "./WorkbookPersonPart";
import { WorkbookRevisionHeaderPart } from "./WorkbookRevisionHeaderPart";
import { WorkbookRevisionLogPart } from "./WorkbookRevisionLogPart";
import { WorkbookStylesPart } from "./WorkbookStylesPart";
import { WorkbookUserDataPart } from "./WorkbookUserDataPart";
import { WorksheetCommentsPart } from "./WorksheetCommentsPart";
import { WorksheetPart } from "./WorksheetPart";
import { WorksheetSortMapPart } from "./WorksheetSortMapPart";
import { WorksheetThreadedCommentsPart } from "./WorksheetThreadedCommentsPart";
import { XmlSignaturePart } from "./XmlSignaturePart";
import { PresentationDocument } from "./PresentationDocument";
import { SpreadsheetDocument } from "./SpreadsheetDocument";
import { WordprocessingDocument } from "./WordprocessingDocument";

export function oxmlInitPackaging() {
    const parts = OxmlPartContainer.registry;
    const packages = OxmlPackage.packages;
    parts[AlternativeFormatImportPart._R + '|' + AlternativeFormatImportPart._C] = AlternativeFormatImportPart;
    parts[CalculationChainPart._R + '|' + CalculationChainPart._C] = CalculationChainPart;
    parts[CellMetadataPart._R + '|' + CellMetadataPart._C] = CellMetadataPart;
    parts[ChartColorStylePart._R + '|' + ChartColorStylePart._C] = ChartColorStylePart;
    parts[ChartDrawingPart._R + '|' + ChartDrawingPart._C] = ChartDrawingPart;
    parts[ChartPart._R + '|' + ChartPart._C] = ChartPart;
    parts[ChartStylePart._R + '|' + ChartStylePart._C] = ChartStylePart;
    parts[ChartsheetPart._R + '|' + ChartsheetPart._C] = ChartsheetPart;
    parts[CommentAuthorsPart._R + '|' + CommentAuthorsPart._C] = CommentAuthorsPart;
    parts[ConnectionsPart._R + '|' + ConnectionsPart._C] = ConnectionsPart;
    parts[ControlPropertiesPart._R + '|' + ControlPropertiesPart._C] = ControlPropertiesPart;
    parts[CoreFilePropertiesPart._R + '|' + CoreFilePropertiesPart._C] = CoreFilePropertiesPart;
    parts[CustomDataPart._R + '|' + CustomDataPart._C] = CustomDataPart;
    parts[CustomDataPropertiesPart._R + '|' + CustomDataPropertiesPart._C] = CustomDataPropertiesPart;
    parts[CustomFilePropertiesPart._R + '|' + CustomFilePropertiesPart._C] = CustomFilePropertiesPart;
    parts[CustomPropertyPart._R + '|' + CustomPropertyPart._C] = CustomPropertyPart;
    parts[CustomXmlMappingsPart._R + '|' + CustomXmlMappingsPart._C] = CustomXmlMappingsPart;
    parts[CustomXmlPart._R + '|' + CustomXmlPart._C] = CustomXmlPart;
    parts[CustomXmlPropertiesPart._R + '|' + CustomXmlPropertiesPart._C] = CustomXmlPropertiesPart;
    parts[CustomizationPart._R + '|' + CustomizationPart._C] = CustomizationPart;
    parts[DiagramColorsPart._R + '|' + DiagramColorsPart._C] = DiagramColorsPart;
    parts[DiagramDataPart._R + '|' + DiagramDataPart._C] = DiagramDataPart;
    parts[DiagramLayoutDefinitionPart._R + '|' + DiagramLayoutDefinitionPart._C] = DiagramLayoutDefinitionPart;
    parts[DiagramPersistLayoutPart._R + '|' + DiagramPersistLayoutPart._C] = DiagramPersistLayoutPart;
    parts[DiagramStylePart._R + '|' + DiagramStylePart._C] = DiagramStylePart;
    parts[DialogsheetPart._R + '|' + DialogsheetPart._C] = DialogsheetPart;
    parts[DigitalSignatureOriginPart._R + '|' + DigitalSignatureOriginPart._C] = DigitalSignatureOriginPart;
    parts[DocumentSettingsPart._R + '|' + DocumentSettingsPart._C] = DocumentSettingsPart;
    parts[DocumentTasksPart._R + '|' + DocumentTasksPart._C] = DocumentTasksPart;
    parts[DrawingsPart._R + '|' + DrawingsPart._C] = DrawingsPart;
    parts[EmbeddedControlPersistenceBinaryDataPart._R + '|' + EmbeddedControlPersistenceBinaryDataPart._C] = EmbeddedControlPersistenceBinaryDataPart;
    parts[EmbeddedControlPersistencePart._R + '|' + EmbeddedControlPersistencePart._C] = EmbeddedControlPersistencePart;
    parts[EmbeddedObjectPart._R + '|' + EmbeddedObjectPart._C] = EmbeddedObjectPart;
    parts[EmbeddedPackagePart._R + '|' + EmbeddedPackagePart._C] = EmbeddedPackagePart;
    parts[EndnotesPart._R + '|' + EndnotesPart._C] = EndnotesPart;
    parts[ExcelAttachedToolbarsPart._R + '|' + ExcelAttachedToolbarsPart._C] = ExcelAttachedToolbarsPart;
    parts[ExtendedChartPart._R + '|' + ExtendedChartPart._C] = ExtendedChartPart;
    parts[ExtendedFilePropertiesPart._R + '|' + ExtendedFilePropertiesPart._C] = ExtendedFilePropertiesPart;
    parts[ExternalWorkbookPart._R + '|' + ExternalWorkbookPart._C] = ExternalWorkbookPart;
    parts[FontPart._R + '|' + FontPart._C] = FontPart;
    parts[FontTablePart._R + '|' + FontTablePart._C] = FontTablePart;
    parts[FooterPart._R + '|' + FooterPart._C] = FooterPart;
    parts[FootnotesPart._R + '|' + FootnotesPart._C] = FootnotesPart;
    parts[GlossaryDocumentPart._R + '|' + GlossaryDocumentPart._C] = GlossaryDocumentPart;
    parts[HandoutMasterPart._R + '|' + HandoutMasterPart._C] = HandoutMasterPart;
    parts[HeaderPart._R + '|' + HeaderPart._C] = HeaderPart;
    parts[ImagePart._R + '|' + ImagePart._C] = ImagePart;
    parts[InternationalMacroSheetPart._R + '|' + InternationalMacroSheetPart._C] = InternationalMacroSheetPart;
    parts[LabelInfoPart._R + '|' + LabelInfoPart._C] = LabelInfoPart;
    parts[LegacyDiagramTextInfoPart._R + '|' + LegacyDiagramTextInfoPart._C] = LegacyDiagramTextInfoPart;
    parts[LegacyDiagramTextPart._R + '|' + LegacyDiagramTextPart._C] = LegacyDiagramTextPart;
    parts[MacroSheetPart._R + '|' + MacroSheetPart._C] = MacroSheetPart;
    parts[MailMergeRecipientDataPart._R + '|' + MailMergeRecipientDataPart._C] = MailMergeRecipientDataPart;
    parts[MainDocumentPart._R + '|' + MainDocumentPart._C] = MainDocumentPart;
    parts[Model3DReferenceRelationshipPart._R + '|' + Model3DReferenceRelationshipPart._C] = Model3DReferenceRelationshipPart;
    parts[NamedSheetViewsPart._R + '|' + NamedSheetViewsPart._C] = NamedSheetViewsPart;
    parts[NotesMasterPart._R + '|' + NotesMasterPart._C] = NotesMasterPart;
    parts[NotesSlidePart._R + '|' + NotesSlidePart._C] = NotesSlidePart;
    parts[NumberingDefinitionsPart._R + '|' + NumberingDefinitionsPart._C] = NumberingDefinitionsPart;
    parts[PivotTableCacheDefinitionPart._R + '|' + PivotTableCacheDefinitionPart._C] = PivotTableCacheDefinitionPart;
    parts[PivotTableCacheRecordsPart._R + '|' + PivotTableCacheRecordsPart._C] = PivotTableCacheRecordsPart;
    parts[PivotTablePart._R + '|' + PivotTablePart._C] = PivotTablePart;
    parts[PowerPointAuthorsPart._R + '|' + PowerPointAuthorsPart._C] = PowerPointAuthorsPart;
    parts[PowerPointCommentPart._R + '|' + PowerPointCommentPart._C] = PowerPointCommentPart;
    parts[PresentationPart._R + '|' + PresentationPart._C] = PresentationPart;
    parts[PresentationPropertiesPart._R + '|' + PresentationPropertiesPart._C] = PresentationPropertiesPart;
    parts[QueryTablePart._R + '|' + QueryTablePart._C] = QueryTablePart;
    parts[QuickAccessToolbarCustomizationsPart._R + '|' + QuickAccessToolbarCustomizationsPart._C] = QuickAccessToolbarCustomizationsPart;
    parts[RdArrayPart._R + '|' + RdArrayPart._C] = RdArrayPart;
    parts[RdRichValuePart._R + '|' + RdRichValuePart._C] = RdRichValuePart;
    parts[RdRichValueStructurePart._R + '|' + RdRichValueStructurePart._C] = RdRichValueStructurePart;
    parts[RdRichValueTypesPart._R + '|' + RdRichValueTypesPart._C] = RdRichValueTypesPart;
    parts[RdRichValueWebImagePart._R + '|' + RdRichValueWebImagePart._C] = RdRichValueWebImagePart;
    parts[RdSupportingPropertyBagPart._R + '|' + RdSupportingPropertyBagPart._C] = RdSupportingPropertyBagPart;
    parts[RdSupportingPropertyBagStructurePart._R + '|' + RdSupportingPropertyBagStructurePart._C] = RdSupportingPropertyBagStructurePart;
    parts[RibbonAndBackstageCustomizationsPart._R + '|' + RibbonAndBackstageCustomizationsPart._C] = RibbonAndBackstageCustomizationsPart;
    parts[RibbonExtensibilityPart._R + '|' + RibbonExtensibilityPart._C] = RibbonExtensibilityPart;
    parts[RichStylesPart._R + '|' + RichStylesPart._C] = RichStylesPart;
    parts[SharedStringTablePart._R + '|' + SharedStringTablePart._C] = SharedStringTablePart;
    parts[SingleCellTablePart._R + '|' + SingleCellTablePart._C] = SingleCellTablePart;
    parts[SlicerCachePart._R + '|' + SlicerCachePart._C] = SlicerCachePart;
    parts[SlicersPart._R + '|' + SlicersPart._C] = SlicersPart;
    parts[SlideCommentsPart._R + '|' + SlideCommentsPart._C] = SlideCommentsPart;
    parts[SlideLayoutPart._R + '|' + SlideLayoutPart._C] = SlideLayoutPart;
    parts[SlideMasterPart._R + '|' + SlideMasterPart._C] = SlideMasterPart;
    parts[SlidePart._R + '|' + SlidePart._C] = SlidePart;
    parts[SlideSyncDataPart._R + '|' + SlideSyncDataPart._C] = SlideSyncDataPart;
    parts[SpreadsheetPrinterSettingsPart._R + '|' + SpreadsheetPrinterSettingsPart._C] = SpreadsheetPrinterSettingsPart;
    parts[StyleDefinitionsPart._R + '|' + StyleDefinitionsPart._C] = StyleDefinitionsPart;
    parts[StylesWithEffectsPart._R + '|' + StylesWithEffectsPart._C] = StylesWithEffectsPart;
    parts[TableDefinitionPart._R + '|' + TableDefinitionPart._C] = TableDefinitionPart;
    parts[TableStylesPart._R + '|' + TableStylesPart._C] = TableStylesPart;
    parts[ThemeOverridePart._R + '|' + ThemeOverridePart._C] = ThemeOverridePart;
    parts[ThemePart._R + '|' + ThemePart._C] = ThemePart;
    parts[ThumbnailPart._R + '|' + ThumbnailPart._C] = ThumbnailPart;
    parts[TimeLineCachePart._R + '|' + TimeLineCachePart._C] = TimeLineCachePart;
    parts[TimeLinePart._R + '|' + TimeLinePart._C] = TimeLinePart;
    parts[UserDefinedTagsPart._R + '|' + UserDefinedTagsPart._C] = UserDefinedTagsPart;
    parts[VbaDataPart._R + '|' + VbaDataPart._C] = VbaDataPart;
    parts[VbaProjectPart._R + '|' + VbaProjectPart._C] = VbaProjectPart;
    parts[ViewPropertiesPart._R + '|' + ViewPropertiesPart._C] = ViewPropertiesPart;
    parts[VmlDrawingPart._R + '|' + VmlDrawingPart._C] = VmlDrawingPart;
    parts[VolatileDependenciesPart._R + '|' + VolatileDependenciesPart._C] = VolatileDependenciesPart;
    parts[WebExTaskpanesPart._R + '|' + WebExTaskpanesPart._C] = WebExTaskpanesPart;
    parts[WebExtensionPart._R + '|' + WebExtensionPart._C] = WebExtensionPart;
    parts[WebSettingsPart._R + '|' + WebSettingsPart._C] = WebSettingsPart;
    parts[WordAttachedToolbarsPart._R + '|' + WordAttachedToolbarsPart._C] = WordAttachedToolbarsPart;
    parts[WordCommentsExtensiblePart._R + '|' + WordCommentsExtensiblePart._C] = WordCommentsExtensiblePart;
    parts[WordprocessingCommentsExPart._R + '|' + WordprocessingCommentsExPart._C] = WordprocessingCommentsExPart;
    parts[WordprocessingCommentsIdsPart._R + '|' + WordprocessingCommentsIdsPart._C] = WordprocessingCommentsIdsPart;
    parts[WordprocessingCommentsPart._R + '|' + WordprocessingCommentsPart._C] = WordprocessingCommentsPart;
    parts[WordprocessingPeoplePart._R + '|' + WordprocessingPeoplePart._C] = WordprocessingPeoplePart;
    parts[WordprocessingPrinterSettingsPart._R + '|' + WordprocessingPrinterSettingsPart._C] = WordprocessingPrinterSettingsPart;
    parts[WorkbookPart._R + '|' + WorkbookPart._C] = WorkbookPart;
    parts[WorkbookPersonPart._R + '|' + WorkbookPersonPart._C] = WorkbookPersonPart;
    parts[WorkbookRevisionHeaderPart._R + '|' + WorkbookRevisionHeaderPart._C] = WorkbookRevisionHeaderPart;
    parts[WorkbookRevisionLogPart._R + '|' + WorkbookRevisionLogPart._C] = WorkbookRevisionLogPart;
    parts[WorkbookStylesPart._R + '|' + WorkbookStylesPart._C] = WorkbookStylesPart;
    parts[WorkbookUserDataPart._R + '|' + WorkbookUserDataPart._C] = WorkbookUserDataPart;
    parts[WorksheetCommentsPart._R + '|' + WorksheetCommentsPart._C] = WorksheetCommentsPart;
    parts[WorksheetPart._R + '|' + WorksheetPart._C] = WorksheetPart;
    parts[WorksheetSortMapPart._R + '|' + WorksheetSortMapPart._C] = WorksheetSortMapPart;
    parts[WorksheetThreadedCommentsPart._R + '|' + WorksheetThreadedCommentsPart._C] = WorksheetThreadedCommentsPart;
    parts[XmlSignaturePart._R + '|' + XmlSignaturePart._C] = XmlSignaturePart;
    packages[PresentationDocument._E] = PresentationDocument;
    packages[SpreadsheetDocument._E] = SpreadsheetDocument;
    packages[WordprocessingDocument._E] = WordprocessingDocument;
}
