export enum OxmlType {
    Unknown = 0,
    StringValue = 1,
    OnOffValue = 2,
    Int16Value = 3,
    Int32Value = 4,
    Int64Value = 5,
    UInt16Value = 6,
    UInt32Value = 7,
    UInt64Value = 8,
    DoubleValue = 9,
    DecimalValue = 10,
    BooleanValue = 11,
    ByteValue = 12,
    SByteValue = 13,
    SingleValue = 14,
    IntegerValue = 15,
    TrueFalseValue = 16,
    TrueFalseBlankValue = 17,
    EnumValue = 18,
    ListValue = 19,
    DateTimeValue = 20,
    HexBinaryValue = 21,
    Base64BinaryValue = 22,
}
